"use client";

import React from "react";
import type { ProofOfPayment, Transaction } from "@/lib/types";
import Image from "next/image";
import {
  pollTransferStatus,
  submitWithdrawalPayment,
  verifyProof,
} from "@/lib/anchors-api";
import { ensureFreighterNetwork, signFreighterTransaction } from "@/lib/wallet";
import { useWallet } from "@/lib/wallet-context";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import {
  CheckCircle2,
  AlertCircle,
  Copy,
  Download,
  Share2,
  ArrowRight,
  ExternalLink,
  Loader2,
  RefreshCw,
  Send,
} from "lucide-react";
import { useState, useCallback } from "react";
import { useEffect } from "react";
import { cn } from "@/lib/utils";

interface ProofOfPaymentProps {
  transaction: Transaction;
  onNewTransfer: () => void;
}

export function ProofOfPaymentView({
  transaction,
  onNewTransfer,
}: ProofOfPaymentProps) {
  const [copied, setCopied] = useState<string | null>(null);
  const [proof, setProof] = useState<ProofOfPayment | null>(
    transaction.proofOfPayment ?? null
  );
  const [txHashInput, setTxHashInput] = useState(transaction.stellarTxHash ?? "");
  const [verifying, setVerifying] = useState(false);
  const [polling, setPolling] = useState(false);
  const [autoStatus, setAutoStatus] = useState<string | null>(null);
  const [verifyError, setVerifyError] = useState<string | null>(null);
  const [showManualHash, setShowManualHash] = useState(false);
  const [signingWithdrawal, setSigningWithdrawal] = useState(false);
  const { status: walletStatus, walletType, address } = useWallet();

  const statusRef = transaction.statusRef ?? "";
  const explorerNetwork = transaction.route.network === "testnet" ? "testnet" : "public";
  const verificationUrl = proof?.verificationUrl ??
    (proof ? `https://stellar.expert/explorer/${explorerNetwork}/tx/${proof.stellarTxHash}` : "");

  const copyToClipboard = useCallback(
    async (text: string, label: string) => {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(null), 2000);
    },
    []
  );

  const handleDownload = useCallback(() => {
    if (!proof) return;
    const content = `
PROOF OF PAYMENT - POP
========================
Transaction ID: ${transaction.id}
Date: ${new Date(proof.timestamp).toLocaleString()}
Status: VERIFIED

TRANSFER DETAILS
-----------------
Sender: ${proof.sender}
Receiver: ${proof.receiver}
Origin: ${proof.originAmount.toLocaleString()} ${proof.originCurrency}
Received: ${proof.destinationAmount.toLocaleString()} ${proof.destinationCurrency}
Exchange Rate: 1 ${proof.originCurrency} = ${proof.exchangeRate} ${proof.destinationCurrency}
Total Fees: ${proof.totalFees.toFixed(2)} ${proof.originCurrency}
Route: ${proof.route}

BLOCKCHAIN VERIFICATION
------------------------
Stellar TX Hash: ${proof.stellarTxHash}
Network: Stellar ${proof.network === "testnet" ? "Testnet" : "Public"}

This proof of payment was generated by POP (Pay On Proof).
Verify on Stellar: ${verificationUrl}
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `POP-${transaction.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [proof, transaction.id, verificationUrl]);

  const createProofFromHash = useCallback(async (hash: string) => {
    setVerifying(true);
    setVerifyError(null);

    try {
      const resolved = await verifyProof({
        transactionId: transaction.id,
        stellarTxHash: hash,
        network: transaction.route.network,
        route: `${transaction.route.originAnchor.name} > ${transaction.route.destinationAnchor.name}`,
        originAmount: transaction.amount,
        originCurrency: transaction.route.originCurrency,
        destinationAmount: transaction.route.receivedAmount,
        destinationCurrency: transaction.route.destinationCurrency,
        exchangeRate: transaction.route.exchangeRate,
        totalFees: transaction.route.feeAmount,
      });
      setProof(resolved);
      return resolved;
    } catch (error) {
      setVerifyError(error instanceof Error ? error.message : "Verification failed");
      return null;
    } finally {
      setVerifying(false);
    }
  }, [transaction]);

  const handleVerify = useCallback(async () => {
    const hash = txHashInput.trim();
    if (!hash) {
      setVerifyError("Enter a Stellar transaction hash.");
      return;
    }
    await createProofFromHash(hash);
  }, [createProofFromHash, txHashInput]);

  const pollAnchorStatus = useCallback(async (options?: { allowSigning?: boolean }) => {
    setPolling(true);
    try {
      const status = await pollTransferStatus({
        transactionId: transaction.id,
        statusRef,
      });

      const origin = status.anchors.find((a) => a.role === "origin");
      const destination = status.anchors.find((a) => a.role === "destination");
      setAutoStatus(
        `Origin: ${origin?.status || "pending"} | Destination: ${
          destination?.status || "pending"
        }`
      );

      const withdrawalPayment = status.withdrawalPayment;
      if (options?.allowSigning && withdrawalPayment) {
        if (walletStatus !== "connected" || walletType !== "freighter" || !address) {
          throw new Error("Connect Freighter wallet before authorizing the anchor payment.");
        }
        setSigningWithdrawal(true);
        await ensureFreighterNetwork(withdrawalPayment.network);
        const signedXdr = await signFreighterTransaction({
          transactionXdr: withdrawalPayment.transactionXdr,
          networkPassphrase: withdrawalPayment.networkPassphrase,
          address,
        });
        const submitted = await submitWithdrawalPayment({
          signedXdr,
          network: withdrawalPayment.network,
          networkPassphrase: withdrawalPayment.networkPassphrase,
        });
        setTxHashInput(submitted.hash);
        await createProofFromHash(submitted.hash);
        return;
      }

      if (status.stellarTxHash) {
        setTxHashInput(status.stellarTxHash);
        await createProofFromHash(status.stellarTxHash);
      }
    } finally {
      setSigningWithdrawal(false);
      setPolling(false);
    }
  }, [
    address,
    createProofFromHash,
    statusRef,
    transaction.id,
    walletStatus,
    walletType,
  ]);

  const handleCheckStatus = useCallback(async () => {
    if (!statusRef) return;
    setVerifyError(null);
    try {
      await pollAnchorStatus({ allowSigning: true });
    } catch (error) {
      setVerifyError(error instanceof Error ? error.message : "Status check failed");
    }
  }, [pollAnchorStatus, statusRef]);

  useEffect(() => {
    if (proof) return;
    if (!statusRef) return;

    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | undefined;

    const run = async () => {
      if (cancelled) return;
      try {
        await pollAnchorStatus();
      } catch (error) {
        if (!cancelled) {
          setAutoStatus(null);
          setVerifyError(error instanceof Error ? error.message : "Auto polling failed");
        }
      }

      timer = setTimeout(run, 15000);
    };

    run();

    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, [pollAnchorStatus, proof, statusRef]);

  if (!proof) {
    return (
      <div className="flex flex-col gap-6 animate-fade-in-up">
        <Card className="rounded-2xl border border-border bg-card p-6">
          <h2 className="text-lg font-bold text-foreground">Complete Anchor Steps</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            Open the anchor links and complete the required flow. POP will keep checking
            the anchor status and create the proof when the Stellar transaction is available.
          </p>
          <div className="mt-4 rounded-xl border border-border bg-muted/20 p-4">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-sm font-semibold text-foreground">
                  {polling ? "Checking anchor status" : "Waiting for anchor settlement"}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {autoStatus || "Status will update automatically after the anchor steps are completed."}
                </p>
              </div>
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                {polling ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <RefreshCw className="h-4 w-4" />
                )}
              </div>
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleCheckStatus}
              disabled={polling || signingWithdrawal || !statusRef}
              className="mt-3 rounded-lg bg-transparent"
            >
              {signingWithdrawal ? (
                <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" />
              ) : (
                <RefreshCw className="mr-2 h-3.5 w-3.5" />
              )}
              {signingWithdrawal ? "Signing anchor payment" : "Check status"}
            </Button>
          </div>

          <div className="mt-4 grid gap-2">
            {transaction.anchorFlows?.originDeposit?.url && (
              <a
                href={transaction.anchorFlows.originDeposit.url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-between rounded-xl border border-border bg-muted/20 px-4 py-3 text-sm"
              >
                <span>
                  Origin deposit ({transaction.anchorFlows.originDeposit.anchorName})
                </span>
                <ExternalLink className="h-4 w-4" />
              </a>
            )}
            {transaction.anchorFlows?.destinationWithdraw?.url && (
              <a
                href={transaction.anchorFlows.destinationWithdraw.url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-between rounded-xl border border-border bg-muted/20 px-4 py-3 text-sm"
              >
                <span>
                  Destination withdrawal ({transaction.anchorFlows.destinationWithdraw.anchorName})
                </span>
                <ExternalLink className="h-4 w-4" />
              </a>
            )}
          </div>

          <div className="mt-5 rounded-xl border border-border bg-muted/10 p-4">
            <button
              type="button"
              onClick={() => setShowManualHash((value) => !value)}
              className="flex w-full items-center justify-between text-left text-sm font-semibold text-foreground"
            >
              Manual hash fallback
              <span className="text-xs text-muted-foreground">
                {showManualHash ? "Hide" : "Show"}
              </span>
            </button>
            {showManualHash && (
              <div className="mt-3 flex flex-col gap-2">
                <label className="text-xs font-semibold text-muted-foreground">
                  Stellar transaction hash
                </label>
                <Input
                  value={txHashInput}
                  onChange={(e) => setTxHashInput(e.target.value)}
                  placeholder="Paste stellar tx hash here"
                />
                <Button
                  type="button"
                  onClick={handleVerify}
                  disabled={verifying}
                  className="mt-2 self-start rounded-xl"
                >
                  {verifying ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Verifying
                    </>
                  ) : (
                    "Verify hash"
                  )}
                </Button>
              </div>
            )}
          </div>

          {verifyError && (
            <p className="mt-3 inline-flex items-start gap-2 text-xs text-destructive">
              <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
              <span>{verifyError}</span>
            </p>
          )}

          <div className="mt-4 flex gap-2">
            <Button variant="outline" onClick={onNewTransfer} className="rounded-xl">
              New Transfer
            </Button>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 animate-fade-in-up">
      {/* Success banner */}
      <div className="flex items-center gap-4 rounded-2xl border border-success/20 bg-success/5 p-5">
        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-success/10">
          <CheckCircle2 className="h-6 w-6 text-success" />
        </div>
        <div>
          <p className="text-lg font-bold text-foreground">
            Payment Verified
          </p>
          <p className="text-sm text-muted-foreground">
            Your transfer was completed and verified on the Stellar network.
          </p>
        </div>
      </div>

      {/* POP Document Card */}
      <Card className="overflow-hidden rounded-2xl border border-border bg-card shadow-2xl shadow-primary/5">
        {/* Branded header */}
        <div className="relative overflow-hidden border-b border-primary/30 bg-primary px-6 py-5">
          <div
            className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,_hsl(263_70%_70%_/_0.3),_transparent_60%)]"
            aria-hidden="true"
          />
          <div className="relative flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Image
                src="/isotipo.png"
                alt="POP"
                width={32}
                height={32}
                className="rounded-lg brightness-200"
              />
              <span className="text-xl font-bold text-primary-foreground">
                Proof of Payment
              </span>
            </div>
            <Badge className="border-primary-foreground/20 bg-primary-foreground/15 text-primary-foreground backdrop-blur-sm">
              <CheckCircle2 className="mr-1.5 h-3 w-3" />
              Verified
            </Badge>
          </div>
        </div>

        {/* Transfer summary */}
        <div className="border-b border-border bg-muted/10 px-4 py-5 sm:px-6 sm:py-6">
          <p className="mb-3 text-center text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
            Transfer Amount
          </p>
          <div className="flex items-center justify-center gap-3 sm:gap-5">
            <div className="text-center">
              <p className="text-2xl font-bold tabular-nums text-foreground sm:text-3xl">
                {proof.originAmount.toLocaleString()}
              </p>
              <p className="mt-0.5 text-sm font-medium text-muted-foreground">
                {proof.originCurrency}
              </p>
            </div>
            <div className="flex h-12 w-12 items-center justify-center rounded-full border border-primary/20 bg-primary/10">
              <ArrowRight className="h-5 w-5 text-primary" />
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold tabular-nums text-primary sm:text-3xl">
                {proof.destinationAmount.toLocaleString()}
              </p>
              <p className="mt-0.5 text-sm font-medium text-muted-foreground">
                {proof.destinationCurrency}
              </p>
            </div>
          </div>
        </div>

        {/* Details grid */}
        <div className="p-4 sm:p-6">
          <div className="flex flex-col gap-3">
            <DetailRow label="Transaction ID" value={transaction.id}>
              <CopyButton
                text={transaction.id}
                label="txId"
                copied={copied}
                onCopy={copyToClipboard}
              />
            </DetailRow>
            <DetailRow
              label="Date & Time"
              value={new Date(proof.timestamp).toLocaleString()}
            />
            <DetailRow label="Route" value={proof.route} />
            <DetailRow
              label="Exchange Rate"
              value={`1 ${proof.originCurrency} = ${proof.exchangeRate} ${proof.destinationCurrency}`}
            />
            <DetailRow
              label="Total Fees"
              value={`${proof.totalFees.toFixed(2)} ${proof.originCurrency}`}
            />

            <Separator className="my-2" />

            {/* Stellar hash section */}
            <div className="flex flex-col gap-2">
              <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                Blockchain Verification
              </span>
              <div className="flex items-center gap-2">
                <code className="flex-1 break-all rounded-xl border border-border bg-muted/30 px-4 py-3 font-mono text-xs leading-relaxed text-foreground">
                  {proof.stellarTxHash}
                </code>
                <CopyButton
                  text={proof.stellarTxHash}
                  label="hash"
                  copied={copied}
                  onCopy={copyToClipboard}
                />
              </div>
              <a
                href={verificationUrl}
                target="_blank"
                rel="noopener noreferrer"
                className={cn(
                  "mt-1 inline-flex items-center gap-1.5 text-xs font-medium text-primary",
                  "transition-colors duration-200 hover:text-primary/80 hover:underline"
                )}
              >
                View on Stellar Explorer
                <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          </div>
        </div>
      </Card>

      {/* Action buttons */}
      <div className="grid grid-cols-1 gap-2 sm:grid-cols-3 sm:gap-3">
        <Button
          onClick={handleDownload}
          variant="outline"
          className={cn(
            "gap-2 rounded-xl bg-transparent",
            "transition-all duration-200",
            "hover:scale-[1.02] hover:shadow-lg hover:shadow-primary/10 hover:border-primary/30",
            "active:scale-[0.98]"
          )}
        >
          <Download className="h-4 w-4" />
          Download
        </Button>
        <Button
          onClick={() => {
            if (navigator.share) {
              navigator.share({
                title: "Proof of Payment - POP",
                text: `Transfer ${proof.originAmount} ${proof.originCurrency} to ${proof.destinationAmount} ${proof.destinationCurrency} verified. TX: ${transaction.id}`,
              });
            } else {
              copyToClipboard(
                `POP Proof: ${transaction.id} | ${proof.originAmount} ${proof.originCurrency} -> ${proof.destinationAmount} ${proof.destinationCurrency} | Hash: ${proof.stellarTxHash}`,
                "share"
              );
            }
          }}
          variant="outline"
          className={cn(
            "gap-2 rounded-xl bg-transparent",
            "transition-all duration-200",
            "hover:scale-[1.02] hover:shadow-lg hover:shadow-primary/10 hover:border-primary/30",
            "active:scale-[0.98]"
          )}
        >
          <Share2 className="h-4 w-4" />
          {copied === "share" ? "Copied!" : "Share"}
        </Button>
        <Button
          onClick={onNewTransfer}
          className={cn(
            "gap-2 rounded-xl bg-primary text-primary-foreground",
            "transition-all duration-200",
            "hover:scale-[1.02] hover:shadow-xl hover:shadow-primary/30",
            "active:scale-[0.98]"
          )}
        >
          <Send className="h-4 w-4" />
          New Transfer
        </Button>
      </div>
    </div>
  );
}

/* ---- Sub-components ---- */

function DetailRow({
  label,
  value,
  children,
}: {
  label: string;
  value: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="shrink-0 text-sm text-muted-foreground">{label}</span>
      <div className="flex items-center gap-1.5">
        <span className="text-right text-sm font-medium text-foreground">
          {value}
        </span>
        {children}
      </div>
    </div>
  );
}

function CopyButton({
  text,
  label,
  copied,
  onCopy,
}: {
  text: string;
  label: string;
  copied: string | null;
  onCopy: (text: string, label: string) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onCopy(text, label)}
      className={cn(
        "shrink-0 rounded-lg p-2 text-muted-foreground",
        "transition-all duration-150",
        "hover:bg-muted hover:text-foreground",
        "active:scale-90"
      )}
      aria-label={`Copy ${label}`}
    >
      {copied === label ? (
        <CheckCircle2 className="h-3.5 w-3.5 text-success" />
      ) : (
        <Copy className="h-3.5 w-3.5" />
      )}
    </button>
  );
}
